include ../Makefile.inc

clean:
	rm -rf *.o *~

project:
#	ln -f -s ${INSTALL}/projects/${PROJ}.h ${INSTALL}/project.h
	ln -f -s ${INSTALL}/projects/${PROJ}.cu ${INSTALL}/project.cu
	ln -f -s ${INSTALL}/projects/${PROJ}.cpp ${INSTALL}/project.cpp


