var annotated_dup =
[
    [ "arch", "d9/d6a/namespacearch.html", [
      [ "buf", "da/d4f/classarch_1_1buf.html", "da/d4f/classarch_1_1buf" ]
    ] ],
    [ "ASTERIX", "d1/d1b/namespace_a_s_t_e_r_i_x.html", [
      [ "VCoords", "d3/d10/struct_a_s_t_e_r_i_x_1_1_v_coords.html", "d3/d10/struct_a_s_t_e_r_i_x_1_1_v_coords" ],
      [ "OrderedVDF", "de/dee/struct_a_s_t_e_r_i_x_1_1_ordered_v_d_f.html", "de/dee/struct_a_s_t_e_r_i_x_1_1_ordered_v_d_f" ],
      [ "UnorderedVDF", "d7/d1a/struct_a_s_t_e_r_i_x_1_1_unordered_v_d_f.html", "d7/d1a/struct_a_s_t_e_r_i_x_1_1_unordered_v_d_f" ],
      [ "PhaseSpaceUnion", "d0/df6/class_a_s_t_e_r_i_x_1_1_phase_space_union.html", "d0/df6/class_a_s_t_e_r_i_x_1_1_phase_space_union" ]
    ] ],
    [ "Dispersion", "dc/db0/namespace_dispersion.html", [
      [ "SI", "d0/d96/class_dispersion_1_1_s_i.html", "d0/d96/class_dispersion_1_1_s_i" ]
    ] ],
    [ "DRO", "db/d48/namespace_d_r_o.html", [
      [ "DataReductionOperator", "d4/d52/class_d_r_o_1_1_data_reduction_operator.html", "d4/d52/class_d_r_o_1_1_data_reduction_operator" ],
      [ "DataReductionOperatorHasParameters", "de/d11/class_d_r_o_1_1_data_reduction_operator_has_parameters.html", "de/d11/class_d_r_o_1_1_data_reduction_operator_has_parameters" ],
      [ "DataReductionOperatorFsGrid", "da/dea/class_d_r_o_1_1_data_reduction_operator_fs_grid.html", "da/dea/class_d_r_o_1_1_data_reduction_operator_fs_grid" ],
      [ "DataReductionOperatorIonosphereElement", "d1/dba/class_d_r_o_1_1_data_reduction_operator_ionosphere_element.html", "d1/dba/class_d_r_o_1_1_data_reduction_operator_ionosphere_element" ],
      [ "DataReductionOperatorIonosphereNode", "d5/d14/class_d_r_o_1_1_data_reduction_operator_ionosphere_node.html", "d5/d14/class_d_r_o_1_1_data_reduction_operator_ionosphere_node" ],
      [ "DataReductionOperatorIonosphereNodeInt", "d3/dfd/class_d_r_o_1_1_data_reduction_operator_ionosphere_node_int.html", "d3/dfd/class_d_r_o_1_1_data_reduction_operator_ionosphere_node_int" ],
      [ "DataReductionOperatorMPIGridCell", "d4/d27/class_d_r_o_1_1_data_reduction_operator_m_p_i_grid_cell.html", "d4/d27/class_d_r_o_1_1_data_reduction_operator_m_p_i_grid_cell" ],
      [ "DataReductionOperatorCellParams", "dc/dc0/class_d_r_o_1_1_data_reduction_operator_cell_params.html", "dc/dc0/class_d_r_o_1_1_data_reduction_operator_cell_params" ],
      [ "DataReductionOperatorDerivatives", "d4/df9/class_d_r_o_1_1_data_reduction_operator_derivatives.html", "d4/df9/class_d_r_o_1_1_data_reduction_operator_derivatives" ],
      [ "DataReductionOperatorBVOLDerivatives", "d8/d46/class_d_r_o_1_1_data_reduction_operator_b_v_o_l_derivatives.html", "d8/d46/class_d_r_o_1_1_data_reduction_operator_b_v_o_l_derivatives" ],
      [ "MPIrank", "d3/d69/class_d_r_o_1_1_m_p_irank.html", "d3/d69/class_d_r_o_1_1_m_p_irank" ],
      [ "MLPepochs", "d8/d36/class_d_r_o_1_1_m_l_pepochs.html", "d8/d36/class_d_r_o_1_1_m_l_pepochs" ],
      [ "MLPerror", "de/d68/class_d_r_o_1_1_m_l_perror.html", "de/d68/class_d_r_o_1_1_m_l_perror" ],
      [ "BoundaryType", "d0/d19/class_d_r_o_1_1_boundary_type.html", "d0/d19/class_d_r_o_1_1_boundary_type" ],
      [ "BoundaryLayer", "dd/d6a/class_d_r_o_1_1_boundary_layer.html", "dd/d6a/class_d_r_o_1_1_boundary_layer" ],
      [ "Blocks", "d3/d01/class_d_r_o_1_1_blocks.html", "d3/d01/class_d_r_o_1_1_blocks" ],
      [ "VariableBVol", "d0/d19/class_d_r_o_1_1_variable_b_vol.html", "d0/d19/class_d_r_o_1_1_variable_b_vol" ],
      [ "VariablePressureSolver", "d6/d9e/class_d_r_o_1_1_variable_pressure_solver.html", "d6/d9e/class_d_r_o_1_1_variable_pressure_solver" ],
      [ "VariablePTensorDiagonal", "de/dfd/class_d_r_o_1_1_variable_p_tensor_diagonal.html", "de/dfd/class_d_r_o_1_1_variable_p_tensor_diagonal" ],
      [ "VariablePTensorOffDiagonal", "d1/d43/class_d_r_o_1_1_variable_p_tensor_off_diagonal.html", "d1/d43/class_d_r_o_1_1_variable_p_tensor_off_diagonal" ],
      [ "DiagnosticFluxB", "df/d63/class_d_r_o_1_1_diagnostic_flux_b.html", "df/d63/class_d_r_o_1_1_diagnostic_flux_b" ],
      [ "DiagnosticFluxE", "db/d84/class_d_r_o_1_1_diagnostic_flux_e.html", "db/d84/class_d_r_o_1_1_diagnostic_flux_e" ],
      [ "VariableRhoThermal", "d9/d24/class_d_r_o_1_1_variable_rho_thermal.html", "d9/d24/class_d_r_o_1_1_variable_rho_thermal" ],
      [ "VariableRhoNonthermal", "dc/dab/class_d_r_o_1_1_variable_rho_nonthermal.html", "dc/dab/class_d_r_o_1_1_variable_rho_nonthermal" ],
      [ "VariableVThermal", "d0/d75/class_d_r_o_1_1_variable_v_thermal.html", "d0/d75/class_d_r_o_1_1_variable_v_thermal" ],
      [ "VariableVNonthermal", "d6/d5d/class_d_r_o_1_1_variable_v_nonthermal.html", "d6/d5d/class_d_r_o_1_1_variable_v_nonthermal" ],
      [ "VariablePTensorThermalDiagonal", "d0/dc0/class_d_r_o_1_1_variable_p_tensor_thermal_diagonal.html", "d0/dc0/class_d_r_o_1_1_variable_p_tensor_thermal_diagonal" ],
      [ "VariablePTensorNonthermalDiagonal", "de/dd1/class_d_r_o_1_1_variable_p_tensor_nonthermal_diagonal.html", "de/dd1/class_d_r_o_1_1_variable_p_tensor_nonthermal_diagonal" ],
      [ "VariablePTensorThermalOffDiagonal", "d1/de8/class_d_r_o_1_1_variable_p_tensor_thermal_off_diagonal.html", "d1/de8/class_d_r_o_1_1_variable_p_tensor_thermal_off_diagonal" ],
      [ "VariablePTensorNonthermalOffDiagonal", "d1/de4/class_d_r_o_1_1_variable_p_tensor_nonthermal_off_diagonal.html", "d1/de4/class_d_r_o_1_1_variable_p_tensor_nonthermal_off_diagonal" ],
      [ "VariableEffectiveSparsityThreshold", "da/ddf/class_d_r_o_1_1_variable_effective_sparsity_threshold.html", "da/ddf/class_d_r_o_1_1_variable_effective_sparsity_threshold" ],
      [ "VariableEnergyDensity", "de/db3/class_d_r_o_1_1_variable_energy_density.html", "de/db3/class_d_r_o_1_1_variable_energy_density" ],
      [ "VariablePrecipitationDiffFlux", "dd/d55/class_d_r_o_1_1_variable_precipitation_diff_flux.html", "dd/d55/class_d_r_o_1_1_variable_precipitation_diff_flux" ],
      [ "VariableMuSpace", "d5/dc9/class_d_r_o_1_1_variable_mu_space.html", "d5/dc9/class_d_r_o_1_1_variable_mu_space" ],
      [ "VariablePrecipitationLineDiffFlux", "db/d62/class_d_r_o_1_1_variable_precipitation_line_diff_flux.html", "db/d62/class_d_r_o_1_1_variable_precipitation_line_diff_flux" ],
      [ "VariableHeatFluxVector", "d9/d02/class_d_r_o_1_1_variable_heat_flux_vector.html", "d9/d02/class_d_r_o_1_1_variable_heat_flux_vector" ],
      [ "VariableNonMaxwellianity", "db/d16/class_d_r_o_1_1_variable_non_maxwellianity.html", "db/d16/class_d_r_o_1_1_variable_non_maxwellianity" ],
      [ "DataReductionOperatorPopulations", "d0/d65/class_d_r_o_1_1_data_reduction_operator_populations.html", "d0/d65/class_d_r_o_1_1_data_reduction_operator_populations" ]
    ] ],
    [ "fieldmodels", "d1/d7b/namespacefieldmodels.html", [
      [ "dipole", "d6/db1/classfieldmodels_1_1dipole.html", "d6/db1/classfieldmodels_1_1dipole" ],
      [ "IMFpotential", "df/d8f/classfieldmodels_1_1_i_m_fpotential.html", "df/d8f/classfieldmodels_1_1_i_m_fpotential" ]
    ] ],
    [ "FieldTracing", "df/dbb/namespace_field_tracing.html", [
      [ "FieldTracingParameters", "d4/d7e/struct_field_tracing_1_1_field_tracing_parameters.html", "d4/d7e/struct_field_tracing_1_1_field_tracing_parameters" ]
    ] ],
    [ "fsgrid", "db/d33/namespacefsgrid.html", [
      [ "FsGrid", "d3/d1a/classfsgrid_1_1_fs_grid.html", null ]
    ] ],
    [ "fsgrids", "d5/d45/namespacefsgrids.html", [
      [ "technical", "dd/d21/structfsgrids_1_1technical.html", "dd/d21/structfsgrids_1_1technical" ]
    ] ],
    [ "projects", "d9/df1/namespaceprojects.html", [
      [ "AlfvenSpeciesParameters", "d8/dcc/structprojects_1_1_alfven_species_parameters.html", "d8/dcc/structprojects_1_1_alfven_species_parameters" ],
      [ "Alfven", "d9/d08/classprojects_1_1_alfven.html", "d9/d08/classprojects_1_1_alfven" ],
      [ "DiffusionSpeciesParameters", "d4/df3/structprojects_1_1_diffusion_species_parameters.html", "d4/df3/structprojects_1_1_diffusion_species_parameters" ],
      [ "Diffusion", "d1/db3/classprojects_1_1_diffusion.html", "d1/db3/classprojects_1_1_diffusion" ],
      [ "DispersionSpeciesParameters", "df/d47/structprojects_1_1_dispersion_species_parameters.html", "df/d47/structprojects_1_1_dispersion_species_parameters" ],
      [ "Dispersion", "d2/d03/classprojects_1_1_dispersion.html", "d2/d03/classprojects_1_1_dispersion" ],
      [ "Distributions", "d9/d69/classprojects_1_1_distributions.html", "d9/d69/classprojects_1_1_distributions" ],
      [ "FirehoseSpeciesParameters", "dc/dea/structprojects_1_1_firehose_species_parameters.html", "dc/dea/structprojects_1_1_firehose_species_parameters" ],
      [ "Firehose", "dc/dd5/classprojects_1_1_firehose.html", "dc/dd5/classprojects_1_1_firehose" ],
      [ "FlowthroughSpeciesParameters", "d6/d04/structprojects_1_1_flowthrough_species_parameters.html", "d6/d04/structprojects_1_1_flowthrough_species_parameters" ],
      [ "Flowthrough", "dd/d62/classprojects_1_1_flowthrough.html", "dd/d62/classprojects_1_1_flowthrough" ],
      [ "FluctuationsSpeciesParameters", "d4/d8b/structprojects_1_1_fluctuations_species_parameters.html", "d4/d8b/structprojects_1_1_fluctuations_species_parameters" ],
      [ "Fluctuations", "dd/d9d/classprojects_1_1_fluctuations.html", "dd/d9d/classprojects_1_1_fluctuations" ],
      [ "HarrisSpeciesParameters", "d4/d89/structprojects_1_1_harris_species_parameters.html", "d4/d89/structprojects_1_1_harris_species_parameters" ],
      [ "Harris", "d2/d61/classprojects_1_1_harris.html", "d2/d61/classprojects_1_1_harris" ],
      [ "IPShockSpeciesParameters", "de/d69/structprojects_1_1_i_p_shock_species_parameters.html", "de/d69/structprojects_1_1_i_p_shock_species_parameters" ],
      [ "IPShock", "db/d4a/classprojects_1_1_i_p_shock.html", "db/d4a/classprojects_1_1_i_p_shock" ],
      [ "KHB", "de/da1/classprojects_1_1_k_h_b.html", "de/da1/classprojects_1_1_k_h_b" ],
      [ "Larmor", "de/d23/classprojects_1_1_larmor.html", "de/d23/classprojects_1_1_larmor" ],
      [ "LossConeSpeciesParameters", "dc/d48/structprojects_1_1_loss_cone_species_parameters.html", "dc/d48/structprojects_1_1_loss_cone_species_parameters" ],
      [ "LossCone", "d9/da0/classprojects_1_1_loss_cone.html", "d9/da0/classprojects_1_1_loss_cone" ],
      [ "MagnetosphereSpeciesParameters", "de/df1/structprojects_1_1_magnetosphere_species_parameters.html", "de/df1/structprojects_1_1_magnetosphere_species_parameters" ],
      [ "Magnetosphere", "df/d57/classprojects_1_1_magnetosphere.html", "df/d57/classprojects_1_1_magnetosphere" ],
      [ "MultiPeakSpeciesParameters", "dc/d72/structprojects_1_1_multi_peak_species_parameters.html", "dc/d72/structprojects_1_1_multi_peak_species_parameters" ],
      [ "MultiPeak", "d4/dc0/classprojects_1_1_multi_peak.html", "d4/dc0/classprojects_1_1_multi_peak" ],
      [ "Project", "db/d19/classprojects_1_1_project.html", "db/d19/classprojects_1_1_project" ],
      [ "TriAxisSearch", "dc/d2c/classprojects_1_1_tri_axis_search.html", "dc/d2c/classprojects_1_1_tri_axis_search" ],
      [ "GaussianPopulation", "dd/d47/structprojects_1_1_gaussian_population.html", "dd/d47/structprojects_1_1_gaussian_population" ],
      [ "ReadGaussianPopulation", "d9/dc9/classprojects_1_1_read_gaussian_population.html", "d9/dc9/classprojects_1_1_read_gaussian_population" ],
      [ "Riemann1", "d4/d0a/classprojects_1_1_riemann1.html", "d4/d0a/classprojects_1_1_riemann1" ],
      [ "Shock", "d5/db6/classprojects_1_1_shock.html", "d5/db6/classprojects_1_1_shock" ],
      [ "Shocktest", "d5/dbc/classprojects_1_1_shocktest.html", "d5/dbc/classprojects_1_1_shocktest" ],
      [ "Template", "df/d44/classprojects_1_1_template.html", "df/d44/classprojects_1_1_template" ],
      [ "test_fp", "da/df8/classprojects_1_1test__fp.html", "da/df8/classprojects_1_1test__fp" ],
      [ "TestHall", "d9/d72/classprojects_1_1_test_hall.html", "d9/d72/classprojects_1_1_test_hall" ],
      [ "verificationLarmor", "dd/d25/classprojects_1_1verification_larmor.html", "dd/d25/classprojects_1_1verification_larmor" ]
    ] ],
    [ "SBC", "d4/de8/namespace_s_b_c.html", [
      [ "CopysphereSpeciesParameters", "d1/d22/struct_s_b_c_1_1_copysphere_species_parameters.html", "d1/d22/struct_s_b_c_1_1_copysphere_species_parameters" ],
      [ "Copysphere", "dd/d8a/class_s_b_c_1_1_copysphere.html", "dd/d8a/class_s_b_c_1_1_copysphere" ],
      [ "DoNotCompute", "d4/db3/class_s_b_c_1_1_do_not_compute.html", "d4/db3/class_s_b_c_1_1_do_not_compute" ],
      [ "InflowSpeciesParameters", "de/d8e/struct_s_b_c_1_1_inflow_species_parameters.html", "de/d8e/struct_s_b_c_1_1_inflow_species_parameters" ],
      [ "Inflow", "de/d6a/class_s_b_c_1_1_inflow.html", "de/d6a/class_s_b_c_1_1_inflow" ],
      [ "IonosphereSpeciesParameters", "d9/d4e/struct_s_b_c_1_1_ionosphere_species_parameters.html", "d9/d4e/struct_s_b_c_1_1_ionosphere_species_parameters" ],
      [ "SphericalTriGrid", "d4/d8d/struct_s_b_c_1_1_spherical_tri_grid.html", "d4/d8d/struct_s_b_c_1_1_spherical_tri_grid" ],
      [ "Ionosphere", "da/d6b/class_s_b_c_1_1_ionosphere.html", "da/d6b/class_s_b_c_1_1_ionosphere" ],
      [ "OutflowSpeciesParameters", "d0/d6c/struct_s_b_c_1_1_outflow_species_parameters.html", "d0/d6c/struct_s_b_c_1_1_outflow_species_parameters" ],
      [ "Outflow", "d5/d71/class_s_b_c_1_1_outflow.html", "d5/d71/class_s_b_c_1_1_outflow" ],
      [ "Maxwellian", "da/ddf/class_s_b_c_1_1_maxwellian.html", "da/ddf/class_s_b_c_1_1_maxwellian" ],
      [ "SysBoundaryCondition", "d8/ddb/class_s_b_c_1_1_sys_boundary_condition.html", "d8/ddb/class_s_b_c_1_1_sys_boundary_condition" ],
      [ "OuterBoundaryCondition", "d2/d68/class_s_b_c_1_1_outer_boundary_condition.html", "d2/d68/class_s_b_c_1_1_outer_boundary_condition" ]
    ] ],
    [ "spatial_cell", "d6/dd0/namespacespatial__cell.html", [
      [ "Population", "d5/d8c/structspatial__cell_1_1_population.html", "d5/d8c/structspatial__cell_1_1_population" ],
      [ "SpatialCell", "d1/d3f/classspatial__cell_1_1_spatial_cell.html", "d1/d3f/classspatial__cell_1_1_spatial_cell" ]
    ] ],
    [ "species", "d3/d67/namespacespecies.html", [
      [ "Species", "d8/ddb/structspecies_1_1_species.html", "d8/ddb/structspecies_1_1_species" ]
    ] ],
    [ "sve", "d5/db2/namespacesve.html", [
      [ "type", "d8/d3d/structsve_1_1type.html", "d8/d3d/structsve_1_1type" ],
      [ "type&lt; __fp16 &gt;", "d4/dcc/structsve_1_1type_3_01____fp16_01_4.html", "d4/dcc/structsve_1_1type_3_01____fp16_01_4" ],
      [ "type&lt; __bf16 &gt;", "da/d7c/structsve_1_1type_3_01____bf16_01_4.html", "da/d7c/structsve_1_1type_3_01____bf16_01_4" ],
      [ "type&lt; float &gt;", "dd/d76/structsve_1_1type_3_01float_01_4.html", "dd/d76/structsve_1_1type_3_01float_01_4" ],
      [ "type&lt; int32_t &gt;", "dd/d36/structsve_1_1type_3_01int32__t_01_4.html", "dd/d36/structsve_1_1type_3_01int32__t_01_4" ],
      [ "type&lt; double &gt;", "d3/d40/structsve_1_1type_3_01double_01_4.html", "d3/d40/structsve_1_1type_3_01double_01_4" ],
      [ "type&lt; int64_t &gt;", "d0/dc0/structsve_1_1type_3_01int64__t_01_4.html", "d0/dc0/structsve_1_1type_3_01int64__t_01_4" ]
    ] ],
    [ "visit_filter_mask_every_nth_cell", "de/dd9/namespacevisit__filter__mask__every__nth__cell.html", [
      [ "MaskEveryNthCell", "d2/df9/classvisit__filter__mask__every__nth__cell_1_1_mask_every_nth_cell.html", "d2/df9/classvisit__filter__mask__every__nth__cell_1_1_mask_every_nth_cell" ]
    ] ],
    [ "visit_filter_mask_list", "dc/d29/namespacevisit__filter__mask__list.html", [
      [ "MaskList", "dd/d35/classvisit__filter__mask__list_1_1_mask_list.html", "dd/d35/classvisit__filter__mask__list_1_1_mask_list" ]
    ] ],
    [ "vlsvinterface", "d5/d64/namespacevlsvinterface.html", [
      [ "Reader", "d1/dcf/classvlsvinterface_1_1_reader.html", "d1/dcf/classvlsvinterface_1_1_reader" ]
    ] ],
    [ "vmesh", "dc/d23/namespacevmesh.html", [
      [ "VelocityBlockContainer", "dd/df7/classvmesh_1_1_velocity_block_container.html", "dd/df7/classvmesh_1_1_velocity_block_container" ],
      [ "VelocityMesh", "dc/d39/classvmesh_1_1_velocity_mesh.html", "dc/d39/classvmesh_1_1_velocity_mesh" ],
      [ "MeshParameters", "d8/dc1/structvmesh_1_1_mesh_parameters.html", "d8/dc1/structvmesh_1_1_mesh_parameters" ],
      [ "MeshWrapper", "d8/db1/structvmesh_1_1_mesh_wrapper.html", "d8/db1/structvmesh_1_1_mesh_wrapper" ]
    ] ],
    [ "aligned_allocator", "d8/dd1/classaligned__allocator.html", "d8/dd1/classaligned__allocator" ],
    [ "analysatorScenario", "d2/dd8/structanalysator_scenario.html", "d2/dd8/structanalysator_scenario" ],
    [ "AtmosphericLayer", "d2/d64/struct_atmospheric_layer.html", "d2/d64/struct_atmospheric_layer" ],
    [ "Boundary", "de/dd6/struct_boundary.html", "de/dd6/struct_boundary" ],
    [ "CardinalIndices", "d0/d9f/struct_cardinal_indices.html", "d0/d9f/struct_cardinal_indices" ],
    [ "CellStructure", "dd/d28/struct_cell_structure.html", "dd/d28/struct_cell_structure" ],
    [ "ColumnOffsets", "d3/d0f/struct_column_offsets.html", "d3/d0f/struct_column_offsets" ],
    [ "CompactSpatialDimension", "d4/d62/struct_compact_spatial_dimension.html", "d4/d62/struct_compact_spatial_dimension" ],
    [ "ConstantField", "de/d55/class_constant_field.html", "de/d55/class_constant_field" ],
    [ "DataArrays", "d8/d04/struct_data_arrays.html", "d8/d04/struct_data_arrays" ],
    [ "DataReducer", "db/da6/class_data_reducer.html", "db/da6/class_data_reducer" ],
    [ "DerivativesData", "d3/dbe/struct_derivatives_data.html", "d3/dbe/struct_derivatives_data" ],
    [ "Dipole", "d6/dfd/class_dipole.html", "d6/dfd/class_dipole" ],
    [ "Distribution", "d8/d4f/class_distribution.html", "d8/d4f/class_distribution" ],
    [ "distributionScenario", "d2/d57/structdistribution_scenario.html", "d2/d57/structdistribution_scenario" ],
    [ "Field", "d5/d94/struct_field.html", "d5/d94/struct_field" ],
    [ "FieldSolverData", "df/d74/struct_field_solver_data.html", "df/d74/struct_field_solver_data" ],
    [ "globalflags", "d6/d33/structglobalflags.html", "d6/d33/structglobalflags" ],
    [ "GPUMemoryManager", "d9/dbb/struct_g_p_u_memory_manager.html", "d9/dbb/struct_g_p_u_memory_manager" ],
    [ "grid_data", "d7/d19/structgrid__data.html", "d7/d19/structgrid__data" ],
    [ "Histogram1D", "d4/de4/class_histogram1_d.html", "d4/de4/class_histogram1_d" ],
    [ "Histogram2D", "d4/dc7/class_histogram2_d.html", "d4/dc7/class_histogram2_d" ],
    [ "Histogram3D", "da/d99/class_histogram3_d.html", "da/d99/class_histogram3_d" ],
    [ "Interpolated_Field", "d7/d79/struct_interpolated___field.html", "d7/d79/struct_interpolated___field" ],
    [ "ipShockScenario", "da/d83/structip_shock_scenario.html", "da/d83/structip_shock_scenario" ],
    [ "ItemStorage", "db/d2f/class_item_storage.html", "db/d2f/class_item_storage" ],
    [ "Kappa", "db/d3e/class_kappa.html", "db/d3e/class_kappa" ],
    [ "Kappa2", "d5/d16/class_kappa2.html", "d5/d16/class_kappa2" ],
    [ "Kappa6", "d9/d76/class_kappa6.html", "d9/d76/class_kappa6" ],
    [ "Limits", "db/db1/struct_limits.html", "db/db1/struct_limits" ],
    [ "LinearHistogram1D", "dd/d8b/class_linear_histogram1_d.html", "dd/d8b/class_linear_histogram1_d" ],
    [ "LinearHistogram2D", "d9/dff/class_linear_histogram2_d.html", "d9/dff/class_linear_histogram2_d" ],
    [ "LinearHistogram3D", "de/dad/class_linear_histogram3_d.html", "de/dad/class_linear_histogram3_d" ],
    [ "LineDipole", "dc/d11/class_line_dipole.html", "dc/d11/class_line_dipole" ],
    [ "LinLogHistogram2D", "d3/d24/class_lin_log_histogram2_d.html", "d3/d24/class_lin_log_histogram2_d" ],
    [ "Logger", "d3/d42/class_logger.html", "d3/d42/class_logger" ],
    [ "LogHistogram1D", "d1/d5c/class_log_histogram1_d.html", "d1/d5c/class_log_histogram1_d" ],
    [ "LogHistogram2D", "db/dd5/class_log_histogram2_d.html", "db/dd5/class_log_histogram2_d" ],
    [ "Maxwell_Boltzmann", "db/d12/class_maxwell___boltzmann.html", "db/d12/class_maxwell___boltzmann" ],
    [ "Monoenergetic", "d9/d72/class_monoenergetic.html", "d9/d72/class_monoenergetic" ],
    [ "NodeComp", "d9/da3/struct_node_comp.html", "d9/da3/struct_node_comp" ],
    [ "NodeCrd", "db/d12/struct_node_crd.html", "db/d12/struct_node_crd" ],
    [ "ObjectFactory", "db/d60/class_object_factory.html", "db/d60/class_object_factory" ],
    [ "ObjectWrapper", "db/d4e/struct_object_wrapper.html", "db/d4e/struct_object_wrapper" ],
    [ "OpenBoundary", "d9/d9e/struct_open_boundary.html", "d9/d9e/struct_open_boundary" ],
    [ "OpenBucketHashtable", "d6/d34/class_open_bucket_hashtable.html", "d6/d34/class_open_bucket_hashtable" ],
    [ "Parameters", "d0/dbf/struct_parameters.html", "d0/dbf/struct_parameters" ],
    [ "Particle", "dd/d47/struct_particle.html", "dd/d47/struct_particle" ],
    [ "ParticleParameters", "d0/d60/struct_particle_parameters.html", "d0/d60/struct_particle_parameters" ],
    [ "PeriodicBoundary", "df/d0f/struct_periodic_boundary.html", "df/d0f/struct_periodic_boundary" ],
    [ "PhysicalConstantsCGS", "db/dba/class_physical_constants_c_g_s.html", "db/dba/class_physical_constants_c_g_s" ],
    [ "PhysicalConstantsnorm", "dd/d9a/class_physical_constantsnorm.html", "dd/d9a/class_physical_constantsnorm" ],
    [ "PhysicalConstantsSI", "dc/d9e/class_physical_constants_s_i.html", "dc/d9e/class_physical_constants_s_i" ],
    [ "precipitationScenario", "d0/d9b/structprecipitation_scenario.html", "d0/d9b/structprecipitation_scenario" ],
    [ "Readparameters", "de/d5d/class_readparameters.html", "de/d5d/class_readparameters" ],
    [ "Reconstructions", "d9/d68/struct_reconstructions.html", "d9/d68/struct_reconstructions" ],
    [ "ReflectBoundary", "d5/d59/struct_reflect_boundary.html", "d5/d59/struct_reflect_boundary" ],
    [ "Scenario", "da/dab/struct_scenario.html", "da/dab/struct_scenario" ],
    [ "SergienkoIvanovParameters", "d1/dfb/struct_sergienko_ivanov_parameters.html", "d1/dfb/struct_sergienko_ivanov_parameters" ],
    [ "setOfPencils", "de/dd5/structset_of_pencils.html", "de/dd5/structset_of_pencils" ],
    [ "shockReflectivityScenario", "d6/de0/structshock_reflectivity_scenario.html", "d6/de0/structshock_reflectivity_scenario" ],
    [ "singleParticleScenario", "d6/d91/structsingle_particle_scenario.html", "d6/d91/structsingle_particle_scenario" ],
    [ "SysBoundary", "dd/d3d/class_sys_boundary.html", "dd/d3d/class_sys_boundary" ],
    [ "test_instatiator", "d0/d5d/structtest__instatiator.html", "d0/d5d/structtest__instatiator" ],
    [ "test_instatiator&lt; N, 0 &gt;", "d7/df6/structtest__instatiator_3_01_n_00_010_01_4.html", "d7/df6/structtest__instatiator_3_01_n_00_010_01_4" ],
    [ "UpwindField", "d6/d2a/struct_upwind_field.html", "d6/d2a/struct_upwind_field" ],
    [ "UserOptions", "da/d0f/class_user_options.html", "da/d0f/class_user_options" ],
    [ "VecSimple", "d7/d8b/class_vec_simple.html", "d7/d8b/class_vec_simple" ],
    [ "VecSVE", "dc/d6a/class_vec_s_v_e.html", "dc/d6a/class_vec_s_v_e" ],
    [ "VecSVEBase", "de/d26/class_vec_s_v_e_base.html", "de/d26/class_vec_s_v_e_base" ],
    [ "VecSVEMask", "d5/d9b/class_vec_s_v_e_mask.html", "d5/d9b/class_vec_s_v_e_mask" ],
    [ "VectorDipole", "da/de8/class_vector_dipole.html", "da/de8/class_vector_dipole" ],
    [ "VlsWriter", "dd/d83/class_vls_writer.html", null ],
    [ "Wavespeeds", "d9/d61/struct_wavespeeds.html", "d9/d61/struct_wavespeeds" ]
];