CMP =CC
LNK =CC
FLAGS =-O3 -fast -openmp -DNDEBUG -DDCCRG_SEND_SINGLE_CELLS -DDCCRG_CELL_DATA_SIZE_FROM_USER
LDFLAGS =-static -openmp

INC_BOOST =-I${HOME}/include
INC_DCCRG =-I${HOME}/include
INC_MPI =
INC_SILO =-I${HOME}/include

LIB_BOOST =-L${HOME}/lib -lboost_mpi -lboost_serialization -lboost_program_options
LIB_MPI =
LIB_SILO = -L${HOME}/lib -lsilo 
LIB_ZOLTAN = -L${HOME}/lib -lzoltan

