CMP = mpic++
LNK = mpic++

FLAGS =
CXXFLAGS = -I $(HOME)/include -L $(HOME)/lib -O3  -funroll-loops -std=c++0x -fopenmp -W -Wall -pedantic -Wno-unused
MATHFLAGS = -ffast-math
LDFLAGS =
LIB_MPI = -lgomp 

LIBRARY_PREFIX = $HOME
LIBRARY_PREFIX_B = $HOME

INC_BOOST =
LIB_BOOST = -lboost_mpi -lboost_serialization -lboost_program_options

INC_ZOLTAN =
LIB_ZOLTAN = -lzoltan

INC_SILO =
LIB_SILO = -lsilo

INC_DCCRG =

LIB_PROFILE = -lprofile
INC_PROFILE =
INC_TOPO =

