CMP =CC
LNK =CC
FLAGS =-Mipa=fast,inline -mp -fast -fastsse -Minline=levels:10 -DNDEBUG
LDFLAGS =-mp

INC_BOOST =-I${HOME}/include
INC_DCCRG =-I${HOME}/include
INC_MPI =
INC_SILO =-I${HOME}/include

LIB_BOOST =-L${HOME}/lib -lboost_mpi -lboost_serialization
LIB_MPI =
LIB_SILO = -L${HOME}/lib -lsilo 
LIB_ZOLTAN = -L${HOME}/lib -lzoltan

