   vis.DefineCurveExpression("operators/Lineout/volumeVx", "rho_v[0] / rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVy", "rho_v[1]/rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVz", "rho_v[2]/rho")
   vis.DefineCurveExpression("operators/Lineout/edgeEx", "E[0]")
   vis.DefineCurveExpression("operators/Lineout/edgeEy", "E[1]")
   vis.DefineCurveExpression("operators/Lineout/edgeEz", "E[2]")
   vis.DefineCurveExpression("operators/Lineout/faceBx", "B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceBy", "B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceBz", "B[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeEx", "E_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeEy", "E_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeEz", "E_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeBx", "B_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeBy", "B_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeBz", "B_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/Total energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>) + (<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6) + 0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>) + 1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/Electric energy", "0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>)")
   vis.DefineCurveExpression("operators/Lineout/Magnetic energy", "(<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6)")
   vis.DefineCurveExpression("operators/Lineout/Kinetic energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>)")
   vis.DefineCurveExpression("operators/Lineout/Thermal energy", "1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/divB", "divergence({<face/Bx>, <face/By>, <face/Bz>})")
   vis.DefineCurveExpression("operators/Lineout/divB_scaled", "relative_size(SpatialGrid) * divergence({<face/Bx>, <face/By>, <face/Bz>}) / B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/faceperBx", "perturbed_B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceperBy", "perturbed_B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceperBz", "perturbed_B[2]")
   vis.DefineCurveExpression("operators/Lineout/V_magnitude", "magnitude(V)")
   vis.DefineCurveExpression("operators/Lineout/facebgBx", "background_B[0]")
   vis.DefineCurveExpression("operators/Lineout/facebgBy", "background_B[1]")
   vis.DefineCurveExpression("operators/Lineout/facebgBz", "background_B[2]")
   vis.DefineCurveExpression("operators/Lineout/J_magnitude", "magnitude(J)")
   vis.DefineCurveExpression("operators/Lineout/Hall_magnitude", "magnitude(Hall)")
   vis.DefineCurveExpression("operators/Lineout/V_parallel_magnitude", "magnitude(V_parallel)")
   vis.DefineCurveExpression("operators/Lineout/V_perp_magnitude", "magnitude(V_perp)")
   vis.DefineCurveExpression("operators/Lineout/alfvenicMachNumber", "V_magnitude*sqrt(1.256637e-6*1.6726e-27*rho)/B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/Heli's criterion", "rho*<volume/Vx>*<volume/Vx>/ (1.0e6*25.0e10)")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitytheta", "if(   and(      eq(<volume/By>, 0.0),      eq(<volume/Bx>, 0.0)   ),   0.0,   acos(<volume/Bz> / B_vol_magnitude))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityux", "<gyrotropicity/u>[0]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuy", "<gyrotropicity/u>[1]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuz", "<gyrotropicity/u>[2]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityminDIagonalPressureDifference", "min(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitymaxDIagonalPressureDifference", "max(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/Temperature", "Pressure / ((rho + 1) * 1.38065e-23)")
   vis.DefineCurveExpression("operators/Lineout/TemperatureTensor_rotated", "<gyrotropicity/R>*TemperatureTensor*transpose(<gyrotropicity/R>)")
   vis.DefineCurveExpression("operators/Lineout/volumeVx", "rho_v[0] / rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVy", "rho_v[1]/rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVz", "rho_v[2]/rho")
   vis.DefineCurveExpression("operators/Lineout/edgeEx", "E[0]")
   vis.DefineCurveExpression("operators/Lineout/edgeEy", "E[1]")
   vis.DefineCurveExpression("operators/Lineout/edgeEz", "E[2]")
   vis.DefineCurveExpression("operators/Lineout/faceBx", "B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceBy", "B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceBz", "B[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeEx", "E_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeEy", "E_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeEz", "E_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeBx", "B_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeBy", "B_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeBz", "B_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/Total energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>) + (<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6) + 0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>) + 1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/Electric energy", "0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>)")
   vis.DefineCurveExpression("operators/Lineout/Magnetic energy", "(<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6)")
   vis.DefineCurveExpression("operators/Lineout/Kinetic energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>)")
   vis.DefineCurveExpression("operators/Lineout/Thermal energy", "1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/divB", "divergence({<face/Bx>, <face/By>, <face/Bz>})")
   vis.DefineCurveExpression("operators/Lineout/divB_scaled", "relative_size(SpatialGrid) * divergence({<face/Bx>, <face/By>, <face/Bz>}) / B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/faceperBx", "perturbed_B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceperBy", "perturbed_B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceperBz", "perturbed_B[2]")
   vis.DefineCurveExpression("operators/Lineout/V_magnitude", "magnitude(V)")
   vis.DefineCurveExpression("operators/Lineout/facebgBx", "background_B[0]")
   vis.DefineCurveExpression("operators/Lineout/facebgBy", "background_B[1]")
   vis.DefineCurveExpression("operators/Lineout/facebgBz", "background_B[2]")
   vis.DefineCurveExpression("operators/Lineout/J_magnitude", "magnitude(J)")
   vis.DefineCurveExpression("operators/Lineout/Hall_magnitude", "magnitude(Hall)")
   vis.DefineCurveExpression("operators/Lineout/V_parallel_magnitude", "magnitude(V_parallel)")
   vis.DefineCurveExpression("operators/Lineout/V_perp_magnitude", "magnitude(V_perp)")
   vis.DefineCurveExpression("operators/Lineout/alfvenicMachNumber", "V_magnitude*sqrt(1.256637e-6*1.6726e-27*rho)/B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/Heli's criterion", "rho*<volume/Vx>*<volume/Vx>/ (1.0e6*25.0e10)")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitytheta", "if(   and(      eq(<volume/By>, 0.0),      eq(<volume/Bx>, 0.0)   ),   0.0,   acos(<volume/Bz> / B_vol_magnitude))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityux", "<gyrotropicity/u>[0]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuy", "<gyrotropicity/u>[1]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuz", "<gyrotropicity/u>[2]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityminDIagonalPressureDifference", "min(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitymaxDIagonalPressureDifference", "max(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/Temperature", "Pressure / ((rho + 1) * 1.38065e-23)")
   vis.DefineCurveExpression("operators/Lineout/TemperatureTensor_rotated", "<gyrotropicity/R>*TemperatureTensor*transpose(<gyrotropicity/R>)")
   vis.DefineCurveExpression("operators/Lineout/volumeVx", "rho_v[0] / rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVy", "rho_v[1]/rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVz", "rho_v[2]/rho")
   vis.DefineCurveExpression("operators/Lineout/edgeEx", "E[0]")
   vis.DefineCurveExpression("operators/Lineout/edgeEy", "E[1]")
   vis.DefineCurveExpression("operators/Lineout/edgeEz", "E[2]")
   vis.DefineCurveExpression("operators/Lineout/faceBx", "B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceBy", "B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceBz", "B[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeEx", "E_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeEy", "E_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeEz", "E_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeBx", "B_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeBy", "B_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeBz", "B_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/Total energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>) + (<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6) + 0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>) + 1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/Electric energy", "0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>)")
   vis.DefineCurveExpression("operators/Lineout/Magnetic energy", "(<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6)")
   vis.DefineCurveExpression("operators/Lineout/Kinetic energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>)")
   vis.DefineCurveExpression("operators/Lineout/Thermal energy", "1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/divB", "divergence({<face/Bx>, <face/By>, <face/Bz>})")
   vis.DefineCurveExpression("operators/Lineout/divB_scaled", "relative_size(SpatialGrid) * divergence({<face/Bx>, <face/By>, <face/Bz>}) / B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/faceperBx", "perturbed_B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceperBy", "perturbed_B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceperBz", "perturbed_B[2]")
   vis.DefineCurveExpression("operators/Lineout/V_magnitude", "magnitude(V)")
   vis.DefineCurveExpression("operators/Lineout/facebgBx", "background_B[0]")
   vis.DefineCurveExpression("operators/Lineout/facebgBy", "background_B[1]")
   vis.DefineCurveExpression("operators/Lineout/facebgBz", "background_B[2]")
   vis.DefineCurveExpression("operators/Lineout/J_magnitude", "magnitude(J)")
   vis.DefineCurveExpression("operators/Lineout/Hall_magnitude", "magnitude(Hall)")
   vis.DefineCurveExpression("operators/Lineout/V_parallel_magnitude", "magnitude(V_parallel)")
   vis.DefineCurveExpression("operators/Lineout/V_perp_magnitude", "magnitude(V_perp)")
   vis.DefineCurveExpression("operators/Lineout/alfvenicMachNumber", "V_magnitude*sqrt(1.256637e-6*1.6726e-27*rho)/B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/Heli's criterion", "rho*<volume/Vx>*<volume/Vx>/ (1.0e6*25.0e10)")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitytheta", "if(   and(      eq(<volume/By>, 0.0),      eq(<volume/Bx>, 0.0)   ),   0.0,   acos(<volume/Bz> / B_vol_magnitude))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityux", "<gyrotropicity/u>[0]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuy", "<gyrotropicity/u>[1]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuz", "<gyrotropicity/u>[2]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityminDIagonalPressureDifference", "min(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitymaxDIagonalPressureDifference", "max(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/Temperature", "Pressure / ((rho + 1) * 1.38065e-23)")
   vis.DefineCurveExpression("operators/Lineout/TemperatureTensor_rotated", "<gyrotropicity/R>*TemperatureTensor*transpose(<gyrotropicity/R>)")
   vis.DefineCurveExpression("operators/Lineout/volumeVx", "rho_v[0] / rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVy", "rho_v[1]/rho")
   vis.DefineCurveExpression("operators/Lineout/volumeVz", "rho_v[2]/rho")
   vis.DefineCurveExpression("operators/Lineout/edgeEx", "E[0]")
   vis.DefineCurveExpression("operators/Lineout/edgeEy", "E[1]")
   vis.DefineCurveExpression("operators/Lineout/edgeEz", "E[2]")
   vis.DefineCurveExpression("operators/Lineout/faceBx", "B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceBy", "B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceBz", "B[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeEx", "E_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeEy", "E_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeEz", "E_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/volumeBx", "B_vol[0]")
   vis.DefineCurveExpression("operators/Lineout/volumeBy", "B_vol[1]")
   vis.DefineCurveExpression("operators/Lineout/volumeBz", "B_vol[2]")
   vis.DefineCurveExpression("operators/Lineout/Total energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>) + (<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6) + 0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>) + 1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/Electric energy", "0.5 * 8.85418781762e-12 * (<volume/Ex>*<volume/Ex> + <volume/Ey>*<volume/Ey> + <volume/Ez>*<volume/Ez>)")
   vis.DefineCurveExpression("operators/Lineout/Magnetic energy", "(<volume/Bx>*<volume/Bx> + <volume/By>*<volume/By> + <volume/Bz>*<volume/Bz>) / (2 * 1.25663706144e-6)")
   vis.DefineCurveExpression("operators/Lineout/Kinetic energy", "0.5 * 1.6726217e-27 * rho * (<volume/Vx>*<volume/Vx> + <volume/Vy>*<volume/Vy> + <volume/Vz>*<volume/Vz>)")
   vis.DefineCurveExpression("operators/Lineout/Thermal energy", "1.5 * Pressure / rho")
   vis.DefineCurveExpression("operators/Lineout/divB", "divergence({<face/Bx>, <face/By>, <face/Bz>})")
   vis.DefineCurveExpression("operators/Lineout/divB_scaled", "relative_size(SpatialGrid) * divergence({<face/Bx>, <face/By>, <face/Bz>}) / B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/faceperBx", "perturbed_B[0]")
   vis.DefineCurveExpression("operators/Lineout/faceperBy", "perturbed_B[1]")
   vis.DefineCurveExpression("operators/Lineout/faceperBz", "perturbed_B[2]")
   vis.DefineCurveExpression("operators/Lineout/V_magnitude", "magnitude(V)")
   vis.DefineCurveExpression("operators/Lineout/facebgBx", "background_B[0]")
   vis.DefineCurveExpression("operators/Lineout/facebgBy", "background_B[1]")
   vis.DefineCurveExpression("operators/Lineout/facebgBz", "background_B[2]")
   vis.DefineCurveExpression("operators/Lineout/J_magnitude", "magnitude(J)")
   vis.DefineCurveExpression("operators/Lineout/Hall_magnitude", "magnitude(Hall)")
   vis.DefineCurveExpression("operators/Lineout/V_parallel_magnitude", "magnitude(V_parallel)")
   vis.DefineCurveExpression("operators/Lineout/V_perp_magnitude", "magnitude(V_perp)")
   vis.DefineCurveExpression("operators/Lineout/alfvenicMachNumber", "V_magnitude*sqrt(1.256637e-6*1.6726e-27*rho)/B_magnitude")
   vis.DefineCurveExpression("operators/Lineout/Heli's criterion", "rho*<volume/Vx>*<volume/Vx>/ (1.0e6*25.0e10)")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitytheta", "if(   and(      eq(<volume/By>, 0.0),      eq(<volume/Bx>, 0.0)   ),   0.0,   acos(<volume/Bz> / B_vol_magnitude))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityux", "<gyrotropicity/u>[0]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuy", "<gyrotropicity/u>[1]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityuz", "<gyrotropicity/u>[2]")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicityminDIagonalPressureDifference", "min(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/gyrotropicitymaxDIagonalPressureDifference", "max(   2.0 * abs(PTensor_rotated[0][0] - PTensor_rotated[1][1]) / (PTensor_rotated[0][0] + PTensor_rotated[1][1]),   2.0 * abs(PTensor_rotated[1][1] - PTensor_rotated[2][2]) / (PTensor_rotated[1][1] + PTensor_rotated[2][2]))")
   vis.DefineCurveExpression("operators/Lineout/Temperature", "Pressure / ((rho + 1) * 1.38065e-23)")
   vis.DefineCurveExpression("operators/Lineout/TemperatureTensor_rotated", "<gyrotropicity/R>*TemperatureTensor*transpose(<gyrotropicity/R>)")

