CMP = mpic++
LNK = mpic++

FLAGS =
CXXFLAGS = -mavx -fabi-version=0 -I $(HOME)/include -L $(HOME)/lib -O3  -funroll-loops -std=c++0x  -W -Wall -pedantic -Wno-unused
MATHFLAGS = -ffast-math
LDFLAGS = -L  $(HOME)/lib
LIB_MPI = 

LIBRARY_PREFIX = $HOME
LIBRARY_PREFIX_B = $HOME

INC_BOOST =
LIB_BOOST = -lboost_mpi -lboost_serialization -lboost_program_options

INC_ZOLTAN =
LIB_ZOLTAN = -lzoltan

INC_SILO =
LIB_SILO = -lsilo

INC_DCCRG =

LIB_PROFILE = -lphiprof
INC_PROFILE =
INC_TOPO =

