# For Frankenstein Hopper1/2 
VECTORCLASS = VEC_FALLBACK_GENERIC
#WID=8
WID=4
USE_CUDA=1

CMP=nvcc -ccbin mpic++ 
LNK = nvcc -ccbin mpic++

CXXFLAGS = -g -O3 -x cu  -DASTERIX_ZFP  -DASTERIX_MLP -DASTERIX_OCTREE  -std=c++20 -Xcompiler -std=c++20 --extended-lambda --expt-relaxed-constexpr -gencode arch=compute_90,code=sm_90 -Xcompiler -fopenmp --generate-line-info -line-info -Xcompiler="-fpermissive"  --extra-device-vectorization
testpackage: CXXFLAGS = -g -O2 -x cu -std=c++20 -Xcompiler -std=c++20 --extended-lambda --expt-relaxed-constexpr -gencode arch=compute_90,code=sm_90 -Xcompiler -fopenmp --generate-line-info -line-info -Xcompiler="-fpermissive"
testpackage: MATHFLAGS = --prec-sqrt=true --prec-div=true --ftz=false --fmad=false

LDFLAGS = -O2 -g -lnvToolsExt
LIB_MPI = -lgomp
LIB_CUDA = -L/usr/local/cuda/lib64
INC_CUDA = -isystem /usr/local/cuda/include


#======== Libraries ===========
LIBRARY_PREFIX = /storage/users/kstppd/port/vlasiator/libraries-hopper2_cuda

INC_BOOST = -isystem /usr/include/boost
LIB_BOOST = -L/usr/include/boost -lboost_program_options

INC_ZOLTAN = -I$(LIBRARY_PREFIX)/include
LIB_ZOLTAN = -L$(LIBRARY_PREFIX)/lib -lzoltan

INC_VLSV = -I$(LIBRARY_PREFIX)/include
LIB_VLSV = -L$(LIBRARY_PREFIX)/lib -lvlsv -Xlinker=-rpath=$(LIBRARY_PREFIX)/vlsv/lib

LIB_PROFILE = -L$(LIBRARY_PREFIX)/lib -lphiprof -Xlinker=-rpath=$(LIBRARY_PREFIX)/lib
INC_PROFILE = -I$(LIBRARY_PREFIX)/include

