name: Generate testpackage reference data on Carrington

on:
  # Only run when triggered manually
  workflow_dispatch:

jobs:
  # This should be kept ~identical to the build_TP job in github-ci.yml
  build_TP:
    # Build Vlasiator with testpackage flags, on the carrington cluster
    # (for subsequent running of the integration test package)
    # also builds the fluxfunction tool
    runs-on: carrington

    steps:
    - name: Clean workspace
      run: |
        RUN_STRING=$( cat << MORO
        rm -rf libraries-carrington library-build testpackage
        rm -f libraries-binaries-carrington.tar.gz testpackage_check_description.txt testpackage-output.tar.gz metrics.txt stdout.txt stderr.txt testpackage_output_variables.txt
        rm -f *.xml
        MORO
        )
        srun --constraint="carrington" bash -c "$RUN_STRING"
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Make clean
      run: VLASIATOR_ARCH=carrington_gcc_openmpi make clean
    - uses: ursg/gcc-problem-matcher@master
    - name: Build libraries
      run: |
        WORKSPACE=`pwd`
        rm -rf library-build
        mkdir -p library-build
        BUILDDIR=library-build
        bash ./fetch_libraries.sh carrington
        srun --constraint="carrington" --job-name CI_ref_build_lib --interactive --nodes=1 -n 1 -c 16 --mem=40G -p short -t 0:10:0 bash -c 'set -e; module purge; ml GCC/13.2.0 OpenMPI/4.1.6-GCC-13.2.0 PMIx/4.2.6-GCCcore-13.2.0 PAPI/7.1.0-GCCcore-13.2.0 Boost/1.83.0-GCC-13.2.0; export VLASIATOR_ARCH=carrington_gcc_openmpi; ./build_fetched_libraries.sh carrington'
        rm -rf $BUILDDIR
    - name: Compile vlasiator (Testpackage build) and fluxfunction
      run: |
        srun --constraint="carrington" --job-name CI_ref_tp_compile --interactive --nodes=1 -n 1 -c 16 --mem=40G -p short -t 0:10:0 bash -c 'set -e; module purge; ml GCC/13.2.0 OpenMPI/4.1.6-GCC-13.2.0 PMIx/4.2.6-GCCcore-13.2.0 PAPI/7.1.0-GCCcore-13.2.0 Boost/1.83.0-GCC-13.2.0; export VLASIATOR_ARCH=carrington_gcc_openmpi; make -j 16 testpackage fluxfunction; sleep 10s'
    - name: Make sure the output binary is visible in lustre
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
        command: ls vlasiator
    - name: Pack libraries and binaries
      run: tar -zcf libraries-binaries-carrington.tar.gz libraries-carrington/ vlasiator fluxfunction
    - name: Upload testpackage binary
      uses: actions/upload-artifact@v4
      with:
        name: vlasiator-reference-testpackage
        path: libraries-binaries-carrington.tar.gz
        if-no-files-found: error
    #- name: Upload build log
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: Testpackage build log
    #    path: build.log
  
  run_testpackage:
    # Run the testpackage on the carrington cluster
    runs-on: carrington
    needs: [build_TP]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Clean libraries
      run: |
        rm -rf libraries-carrington
        rm -f libraries-binaries-carrington.tar.gz
    - name: Download testpackage binary
      uses: actions/download-artifact@v4
      with:
        name: vlasiator-reference-testpackage
    - name: Unpack libraries and binaries
      run: tar -zxf libraries-binaries-carrington.tar.gz
    - name: Run testpackage
      id: run
      run: |
        chmod +x $GITHUB_WORKSPACE/vlasiator
        cd testpackage
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/libraries-carrington/lib
        # Fudge the run script
        sed -i 's/\/proj\/USERNAME\/BINARYNAME/$GITHUB_WORKSPACE\/vlasiator/' ./small_test_carrington.sh
        sed -i 's/create_verification_files=0/create_verification_files=1/' ./small_test_carrington.sh
        sbatch -W -o testpackage_run_output.txt --job-name CI_ref_generate ./small_test_carrington.sh
        cat testpackage_run_output.txt
    - name: Generate reference fluxfunction files
      run: |
        echo "Generating fluxfunction files for revision $REFERENCE_REVISION"
        chmod +x $GITHUB_WORKSPACE/fluxfunction
        srun --job-name fluxtest --constraint="carrington" -N 1 -c 1 --mem=1G bash -c "module purge; ml GCC/13.2.0 OpenMPI/4.1.6-GCC-13.2.0 PMIx/4.2.6-GCCcore-13.2.0 PAPI/7.1.0-GCCcore-13.2.0  Boost/1.83.0-GCC-13.2.0; $GITHUB_WORKSPACE/fluxfunction testpackage/run_*/Magnetosphere_small/bulk.0000001.vlsv equatorial.bin"
        srun --job-name fluxtest --constraint="carrington" -N 1 -c 1 --mem=1G bash -c "module purge; ml GCC/13.2.0 OpenMPI/4.1.6-GCC-13.2.0 PMIx/4.2.6-GCCcore-13.2.0 PAPI/7.1.0-GCCcore-13.2.0  Boost/1.83.0-GCC-13.2.0; $GITHUB_WORKSPACE/fluxfunction testpackage/run_*/Magnetosphere_polar_small/bulk.0000001.vlsv polar.bin"
        chmod 775 polar.bin equatorial.bin
        cp equatorial.bin $REFERENCE_REVISION
        cp polar.bin $REFERENCE_REVISION
        # No longer overwrites files in $reference_dir/CI_reference/ but places in proper folder
    # We don't bother to create artefacts or anything here.
