name: Report
# see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run
on:
  workflow_run:
    workflows: ["PR LLM auto-review"]
    types: [completed]

permissions:
  pull-requests: write
  issues: write

jobs:
  llm_report:
    runs-on: ubuntu-latest
    steps:
      - name: download LLM output
        # Note we are downloading an artifact from a
        # *different* workflow here.
        uses: ursg/action-download-artifact@v2
        with:
          name: llm-output
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: download PR number
        uses: ursg/action-download-artifact@v2
        with:
          name: pr_number
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Ser PR number env variable
        run: |
            echo "PR_NUMBER=`cat pr_number`" >> $GITHUB_ENV
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
             message-path: output.txt
             issue: ${{ env.PR_NUMBER }}
